#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo "usage: $(basename $0) host (example: $(basename $0) 192.168.1.1)" >&2
    exit 1
fi

top_ports=$(sudo nmap -sTU --top-ports 100 -v -oG - 2> /dev/null | grep "# Ports")

tcp_ports=$(sed 's/.*TCP[^;]*;\([^)]*\).*/\1/g' <<< $top_ports)
sudo masscan -oL - -sT --rate 100 --wait 1 -p "$tcp_ports" "$1" 2> /dev/null |
    while read line
    do
        set -- $line
        if [ "$1" = "open" ]
        then
            echo host:$4:tcp:$3
        fi
    done
    
udp_ports=$(sed 's/.*UDP[^;]*;\([^)]*\).*/\1/g' <<< $top_ports)
sudo masscan -oL - -sU --rate 100 --wait 1 -p "$udp_ports" "$1" 2> /dev/null |
    while read line
    do
        set -- $line
        if [ "$1" = "open" ]
        then
            echo host:$4:udp:$3
        fi
    done
