#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo "usage: $(basename $0) network (example: $(basename $0) 192.168.1.0/24)" >&2
    exit 1
fi

network="$1"
sudo masscan -oL - --ping --rate 100 --wait 1 "$1" 2>/dev/null |
    while read line
    do
        set -- $line
        if [ "$1" = "open" ]
        then
            echo host:$4
        fi
    done
