#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo "usage: $(basename $0) network (example: $(basename $0) 10.0.0.0/8)" >&2
    exit 1
fi

network="$1"

routers=()
for router in $(ipcalc -S24 --no-decorate "$network")
do
    routers+=(${router%.*}.1 ${router%.*}.254)
done

declare -A networks
tr ' ' '\n' <<< "${routers[@]}" |
    sudo masscan -iL - -oL - --ping --rate 100 --wait 1 2>/dev/null |
    while read line
    do
        set -- $line
        if [ "$1" = "open" ] && [[ ! -v networks[$4] ]]
        then
            networks[$4]=1
            echo net:$(ipcalc "$4"/24 -n --no-decorate)/24
        fi
    done
